import json
import os
from pymongo import MongoClient

# TECHNICAL NOTE: Connecting from WSL2 (Linux) to a MongoDB instance hosted on Windows 
# can be challenging due to network virtualization. Since 'localhost' refers to the 
# Linux container itself and not the Windows host, I found that using the specific 
# WSL2 virtual gateway IP (172.17.16.1) was the only way to successfully bridge 
# the connection and ensure stable communication between the environments.
WIN_IP = "172.17.16.1"

try:
    print(f"Connecting to MongoDB on Windows ({WIN_IP})...")
    # Timeout set to 5 seconds to avoid long hangs if the bridge IP is unreachable
    client = MongoClient(f'mongodb://{WIN_IP}:27017/', serverSelectionTimeoutMS=5000)
    
    # Sanity check to confirm server availability before processing files[cite: 17]
    client.server_info() 
    print("CONNECTION ESTABLISHED. Starting data import...")
    
    # Define database and collection according to the internship project structure[cite: 17]
    db = client['estagio_desporto']
    collection = db['articles']

    # Path to the cleaned and deduplicated data generated by clean_data.py[cite: 6, 16]
    input_folder = "data/cleaned"
    
    if not os.path.exists(input_folder):
        print(f"Error: Folder '{input_folder}' not found. Please run clean_data.py first.")
    else:
        files = [f for f in os.listdir(input_folder) if f.endswith('.json')]
        total_inserted = 0

        for file in files:
            file_path = os.path.join(input_folder, file)
            with open(file_path, 'r', encoding='utf-8') as f:
                articles = json.load(f)
                if articles:
                    # Bulk insertion for improved performance[cite: 17]
                    result = collection.insert_many(articles)
                    count = len(result.inserted_ids)
                    total_inserted += count
                    print(f" > {file}: {count} articles imported.")

        print("-" * 50)
        print(f"IMPORT COMPLETED: {total_inserted} documents now in MongoDB.")

except Exception as e:
    print(f"Unexpected Error during MongoDB connection/import: {e}")